state:
  strength: 0
  charisma: 0
cmds:
  play_animation:
    duration: 1
line: 0
passage: Start
characters:
  Alice:
    description: A character named Alice.
  Bob:
    description: A character named Bob.
